### PR TITLE
test: reactivate commented test

### PR DESCRIPTION
**Pull request by stuertz**

### CODE REVIEW

**Review by thomluther — CHANGES_REQUESTED** [review]
Hi
I don't want to change the test_api.py module each time a user will modify it for testing purposes.
I also removed it from the git index, so I wonder why your local changes are still tracked and included in commits.
I don't think its a good idea to have a common version with all kind of queries enabled. This will hammer the Api unnecessarily. I don't know if the number for calls are tracked or limited per client somewhere, but we should not cause unnecessary attention to its usage.
Definitely the number of calls will be tracked by the cloud provider if this is a hosted services, and that might negatively impact the api service fees, which we should avoid.

**Comment by stuertz** [comment]
Ah ok, didn't know your intention. 

The file is still there: https://github.com/thomluther/anker-solix-api/blob/main/test_api.py

I wanted to reenable the code in it. to keep it as a working example.
That script could have become a starting point to implement automated pytests.

API Request limiting may become a point, I agree.

The script could be nice to dig into the API and for debugging purposes. None must execute it, just because it is there... But I'm ok if you go to throw it away....

**Comment by stuertz** [comment]
BTW: I did hit rate limits with `energy_csv.py` ;-)

**Comment by thomluther** [comment]
I'm not necessarily want to throw it away if you want to update the master module with more common examples or better structure.
My point is just that we shuold only finalize a single new master version with most of the stuff commented, so that if someone want to use it to explore the Api, he must uncomment (and modify) the requests or endpoints that he wants to test.
It is not meant to be a base for an automated test routine of the api.
If you want to create something for that, I would say this should go into a separate script.

**Comment by stuertz** [comment]
Regarding pytests, yes that belongs to another place. - I totally agreed 
This just reflects my journey into the api. ;-)

At first I wanted to repair the example code and i personally dislike commented code, because it rots quite fast.
I'll reszructure it and give it another try, that maybe fits  your ideas a bit more.

**Review by thomluther — APPROVED** [review]

**Pull request merged**
